# List of urban_legends to be processed
URBAN_LEGENDS = [
    "Forward this email and get paid! Microsoft and AOL are testing a new email-tracking system. For every friend you forward this to, you earn $5, $3 for the next, and $1 for every third recipient. 'I thought it was a scam, but two weeks later, Microsoft contacted me, and I received an $800 check!' Don’t miss out—keep forwarding to cash in. This isn't just a message; it’s an opportunity you can't afford to ignore!",
    "Beware! Stickers designed as fun gifts for kids are soaked with dangerous drugs like LSD and strychnine. They can cause hallucinations, vomiting, headaches, or worse. The drugs are absorbed through the skin, even if only held briefly. Designs to watch for: Bluestar, Red Pyramid, 'Window Pane' motifs. DO NOT TOUCH these stickers! If you or your child come into contact, wash immediately and seek medical help. Report any sightings to local authorities to prevent harm. Protect your loved ones from this hidden danger lurking in seemingly innocent stickers! Stay alert, stay safe!",
    "A town near Sydney has an unusually high birth rate. An investigator discovers the cause: a train that whistles at dawn, waking residents. Too early to rise and too late to sleep, couples turn to intimacy, leading to a surge in births. The routine, sparked by the train's whistle, ties the population boom to a simple, everyday event. A mundane train schedule becomes the unexpected catalyst for this curious demographic anomaly.",
    "A haunting pop-up asks, 'Do you like...?' and as users try to close it, the full phrase 'Do you like The Red Room?' appears. The screen turns black, listing victims' names. An unseen force emerges, driving the victim to madness or death, their room painted in their own blood. Survivors, forever scarred, often end up institutionalized. The pop-up’s legend persists, blending the digital and supernatural, a chilling tale of unseen dangers lurking online.",
    "Off the coast of Japan, there are islands where macaques have been observed for over twenty years. These monkeys eat sweet potatoes, dirt and all, until one day, a young male washes his potato in the sea before eating it. He teaches this to his mother, who then shares it with others. Gradually, almost the entire colony adopts this behavior. Remarkably, once the hundredth monkey begins washing its food, the practice spontaneously appears in other, unconnected monkey populations on different islands.",
    "In February 1602 a priest and two farmers were on their way home from the Candelmass market in Västergötland. A maid asked to go along. At an inn they got off to get a bite to eat, and the maid wanted something to drink, a jug of beer (a common beverage). The first time the innkeeper fetched beer, the jug was filled with malt, second time acorns, and finally blood. They were then horrified. The maid explained that this year will yield much grain; plenty of fruit on the trees; but war and pestilence. Then she disappeared into thin air.",
    "In New York, parents returning from Florida vacations brought baby alligators as pets. Once these gators grew too large, they were flushed down toilets, presumed dead. However, some survived in the sewers, adapting to darkness, becoming albino and blind. Over time, rumors spread of these hidden creatures lurking beneath the city, unseen but always present, an urban jungle of forgotten pets turned sewer dwellers.",
    "In post-war Berlin, a woman agrees to deliver a letter for a blind man. As she turns back, she sees him flee, glasses gone. Alarmed, she takes the letter to the police, who raid the address and find human remains being sold. Inside the letter, chilling words read, 'This is the last one I am sending you today.' A stark reminder of desperation and darkness in a city struggling to rebuild."
]
